### ISSUE TITLE
Can't run init script - dumb error

### ISSUE THREAD

**Issue by julie-sullivan** [Bohdan-Khomtchouk/PubData#9]
Sorry this is likely a silly problem. 

```
julie ~/git/PubData/interface $ ./GUI.py
Traceback (most recent call last):
  File "./GUI.py", line 11, in <module>
    from importlib import reload
ImportError: cannot import name reload
julie ~/git/PubData/interface $ python --version
Python 2.7.6
```

Suggestions? What have I done wrong?

Thanks!

**Comment by kasravnd** [comment]
Some parts of the code are on develop, and are not compatible with both python versions. For now the supported version is 3.X. Please try with that.

**Comment by Bohdan-Khomtchouk** [comment]
Yes, for now please use Python 3.X, not 2.X.
